// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-listings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function publicSupabase() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_listings_default = defineTool({
  name: "search_listings",
  title: "Search listings",
  description: "Search active, approved classified ads on Tout Suite Annonces. Filter by keyword, location, price range, and sort. Returns up to 20 listings.",
  inputSchema: {
    query: z.string().optional().describe("Keyword to match in title/description."),
    location: z.string().optional().describe("City or region substring."),
    min_price: z.number().nonnegative().optional(),
    max_price: z.number().nonnegative().optional(),
    sort: z.enum(["recent", "price_asc", "price_desc"]).optional().describe("Sort order (default: recent)."),
    limit: z.number().int().min(1).max(20).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, location, min_price, max_price, sort, limit }) => {
    const supabase = publicSupabase();
    let q = supabase.from("listings").select("id, title, description, price, currency, location, images, is_premium, is_urgent, created_at").eq("is_active", true).eq("moderation_status", "approved");
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    if (location) q = q.ilike("location", `%${location}%`);
    if (typeof min_price === "number") q = q.gte("price", min_price);
    if (typeof max_price === "number") q = q.lte("price", max_price);
    if (sort === "price_asc") q = q.order("price", { ascending: true, nullsFirst: false });
    else if (sort === "price_desc") q = q.order("price", { ascending: false, nullsFirst: false });
    else q = q.order("created_at", { ascending: false });
    q = q.limit(limit ?? 10);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const items = (data ?? []).map((l) => ({
      ...l,
      url: `https://toutsuiteannonces.com/annonce/${l.id}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/get-listing.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function publicSupabase2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_listing_default = defineTool2({
  name: "get_listing",
  title: "Get listing details",
  description: "Fetch the full details of a single listing by its ID.",
  inputSchema: {
    id: z2.string().uuid().describe("The listing UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = publicSupabase2();
    const { data, error } = await supabase.from("listings").select(
      "id, title, description, price, currency, price_type, location, images, is_premium, is_urgent, views_count, category_id, created_at, published_at"
    ).eq("id", id).eq("is_active", true).eq("moderation_status", "approved").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Listing not found." }], isError: true };
    }
    const listing = { ...data, url: `https://toutsuiteannonces.com/annonce/${data.id}` };
    return {
      content: [{ type: "text", text: JSON.stringify(listing, null, 2) }],
      structuredContent: { listing }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function publicSupabase3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all classified ad categories available on Tout Suite Annonces.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = publicSupabase3();
    const { data, error } = await supabase.from("categories").select("id, name, slug").order("name", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "tout-suite-annonces-mcp",
  title: "Tout Suite Annonces",
  version: "0.1.0",
  instructions: "Tools to browse classified ads on Tout Suite Annonces (Senegal). Use `list_categories` to discover categories, `search_listings` to find ads by keyword/location/price, and `get_listing` to fetch full details for a specific ad.",
  tools: [search_listings_default, get_listing_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
